AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB Table for category

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd

Resources:
  ItemTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-app-customers-table'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: customer_id
          AttributeType: S
      KeySchema:
        - AttributeName: customer_id
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: !Ref Environment
