AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB Table for category

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd

Resources:
  ItemTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-app-category-table'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: customer_id
          AttributeType: S
        - AttributeName: category_id
          AttributeType: S
      KeySchema:
        - AttributeName: customer_id
          KeyType: HASH
        - AttributeName: category_id
          KeyType: RANGE
      Tags:
        - Key: Environment
          Value: !Ref Environment
