AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito User Pool with Google OAuth

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
  CallbackUrl:
    Type: String
    Default: http://localhost:3000/auth/callback
  LogoutUrl:
    Type: String
    Default: http://localhost:3000/login
  GitHubPagesCallbackUrl:
    Type: String
    Default: 'https://a-nkt.github.io/kakeibo/auth/callback'
  GitHubPagesLogoutUrl:
    Type: String
    Default: 'https://a-nkt.github.io/kakeibo/login'

Conditions:
  HasGitHubPages: !Not [!Equals [!Ref GitHubPagesCallbackUrl, '']]

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${Environment}-${AWS::StackName}-user-pool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: name
          Required: false
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub ai-kakeibo-${Environment}
      UserPoolId: !Ref UserPool

  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: Google
      ProviderType: Google
      ProviderDetails:
        client_id: '{{resolve:ssm:/dev/app/google/client-id}}'
        client_secret: '{{resolve:ssm:/dev/app/google/client-secret}}'
        authorize_scopes: openid email profile
      AttributeMapping:
        email: email
        name: name
        username: sub

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: GoogleIdentityProvider
    Properties:
      ClientName: !Sub ${Environment}-${AWS::StackName}-client
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - Google
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - !Ref CallbackUrl
        - !If [HasGitHubPages, !Ref GitHubPagesCallbackUrl, !Ref 'AWS::NoValue']
      LogoutURLs:
        - !Ref LogoutUrl
        - !If [HasGitHubPages, !Ref GitHubPagesLogoutUrl, !Ref 'AWS::NoValue']
      PreventUserExistenceErrors: ENABLED

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolId

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolClientId

  CognitoDomain:
    Description: Cognito Hosted UI Domain
    Value: !Sub ai-kakeibo-${Environment}.auth.${AWS::Region}.amazoncognito.com
    Export:
      Name: !Sub ${AWS::StackName}-CognitoDomain

  GoogleIdpResponseUrl:
    Description: URL to set in Google Cloud Console as redirect URI
    Value: !Sub https://ai-kakeibo-${Environment}.auth.${AWS::Region}.amazoncognito.com/oauth2/idpresponse
