AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
  CategoryName:
    Type: String
  AppName:
    Type: String

Globals:
  Function:
    Timeout: 30
    Runtime: python3.13
    Architectures:
      - arm64
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        ITEM_TABLE_NAME: !Sub '${Environment}-app-item-table'
        CATEGORY_TABLE_NAME: !Sub '${Environment}-app-category-table'
        CUSTOMER_TABLE_NAME: !Sub '${Environment}-app-customers-table'

Resources:
  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-${CategoryName}-${AppName}-item-register-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Environment}-app-item-table'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Environment}-app-category-table'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Environment}-app-customers-table'

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt FunctionRole.Arn
      CodeUri: src/app/
      Handler: lambda_function.lambda_handler
      Layers:
        - arn:aws:lambda:ap-northeast-1:017000801446:layer:AWSLambdaPowertoolsPythonV3-python313-arm64:15
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: item-register
          POWERTOOLS_LOG_LEVEL: INFO
      Events:
        ItemRegister:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /api/v1/item/regist
            Method: POST
        ItemList:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /api/v1/item/list
            Method: GET
        ItemUpdate:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /api/v1/item/update
            Method: PUT
        ItemDelete:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /api/v1/item/delete
            Method: DELETE
        CategoryRegister:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /api/v1/category/regist
            Method: POST
        CategoryList:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /api/v1/category/list
            Method: GET
        CategoryDelete:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /api/v1/category/delete
            Method: DELETE
        CategoryUpdate:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /api/v1/category/update
            Method: PUT
        BudgetRegister:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /api/v1/customer/budget/regist
            Method: POST
        BudgetGet:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /api/v1/customer/budget
            Method: GET

  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub /aws/lambda/${Function}
      RetentionInDays: 90

  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub '${Environment}-${CategoryName}-${AppName}-api'
      StageName: v1
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'GET, POST, PUT, DELETE, OPTIONS'"
        AllowHeaders: "'Content-Type'"

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${Api}.execute-api.${AWS::Region}.amazonaws.com'
