AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito User Pool with Google OAuth

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  GoogleClientIdParam:
    Type: String
    Default: /app/google/client-id
    Description: SSM Parameter name for Google OAuth Client ID
  GoogleClientSecretParam:
    Type: String
    Default: /app/google/client-secret
    Description: SSM Parameter name for Google OAuth Client Secret
  CallbackUrl:
    Type: String
    Default: http://localhost:3000/auth/callback
    Description: OAuth callback URL
  LogoutUrl:
    Type: String
    Default: http://localhost:3000/login
    Description: Logout redirect URL

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AWS::StackName}-user-pool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: name
          Required: false
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub ${AWS::StackName}-${AWS::AccountId}
      UserPoolId: !Ref UserPool

  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: Google
      ProviderType: Google
      ProviderDetails:
        client_id: !Sub '{{resolve:ssm-secure:${GoogleClientIdParam}}}'
        client_secret: !Sub '{{resolve:ssm-secure:${GoogleClientSecretParam}}}'
        authorize_scopes: openid email profile
      AttributeMapping:
        email: email
        name: name
        picture: picture
        username: sub

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: GoogleIdentityProvider
    Properties:
      ClientName: !Sub ${AWS::StackName}-client
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - Google
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - !Ref CallbackUrl
      LogoutURLs:
        - !Ref LogoutUrl
      PreventUserExistenceErrors: ENABLED

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolId

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolClientId

  CognitoDomain:
    Description: Cognito Hosted UI Domain
    Value: !Sub ${AWS::StackName}-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com
    Export:
      Name: !Sub ${AWS::StackName}-CognitoDomain

  GoogleIdpResponseUrl:
    Description: URL to set in Google Cloud Console as redirect URI
    Value: !Sub https://${AWS::StackName}-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com/oauth2/idpresponse
